"""
UI selectors for the target portal.

=======================================================================
  EXAMPLE SELECTORS — you MUST customise these for your own portal.
=======================================================================

These selectors were written against a sample enterprise reporting portal.
They use Playwright locator strategies (CSS, role, text, label).  When you
adapt this template to a different site:

  1. Use `playwright codegen <URL>` to record the flow and discover selectors.
  2. Replace the values below with your portal's selectors.
  3. Prefer role/label selectors over brittle CSS nth-child selectors.
"""


# -- Login page -----------------------------------------------------------
LOGIN_EMAIL_PLACEHOLDER = "Your email address"
LOGIN_PASSWORD_PLACEHOLDER = "Your portal password"

# -- MFA / 2-step verification -------------------------------------------
MFA_PROMPT_TEXT = "2-step verification"

# -- Post-login navigation ------------------------------------------------
# Regex pattern that matches the welcome banner (used to locate the nav link).
import re
WELCOME_BANNER_PATTERN = re.compile(r"Welcome .+@.+\..+")

# Link text to reach the reports section after login.
REPORTS_LINK_TEXT = "My Reports"

# -- Entity / report selection --------------------------------------------
# These CSS class names come from the example portal's BI framework.
# Your portal will have different class names — inspect the DOM to find them.
ENTITY_ITEM_CSS = ".mstrIcon-container, .mstrListViewItem, .mstrLargeIconViewItem"

# Role + name of the link that runs a dashboard for a selected entity.
RUN_DASHBOARD_LINK_NAME = "Run Dashboard"

# -- Date filter ----------------------------------------------------------
# These IDs are dynamically generated by the portal framework and WILL break
# when the portal is updated.  Inspect the DOM and update as needed.
DATE_FILTER_REMOVE_ALL_ID = "#id_mstr140"
DATE_FILTER_ADD_ID = "#id_mstr137"

# -- Export / download ----------------------------------------------------
CONTEXT_MENU_LABEL = "Context Menu"
EXPORT_MENU_TEXT = "Export"
EXPORT_DATA_MENUITEM_NAME = "Data"
DOWNLOAD_BUTTON_NAME = "Download"

# -- Misc UI elements ----------------------------------------------------
FILTER_PANEL_CLOSE_CSS = ".mstrmojo-VIBoxPanelContainer-closeBtn"
RESET_VIEW_CSS = "div:nth-child(7) > .btn > .icn"  # Fragile — update if UI changes.
ERROR_PAGE_TEXT = "requested URL cannot be retrieved"

# -- Context-menu item CSS ------------------------------------------------
CONTEXT_MENU_ITEM_CSS = ".mstrmojo-ui-Menu-item"
